name: ci-cd-pipeline

on:
  pull_request:
    branches: [ main ]

permissions:
  pull-requests: write

jobs:
  comment-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: CI/CD en acción. Ejecutando tareas ...
          reactions: rocket
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest tests/test_prediction.py -v